name: Sync

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/dothq/ffr"
        source_branch: "release"
        destination_branch: "ff-gha"
        github_token: ${{ secrets.ROBOT_TOKEN }}
